import 'dotenv/config';
import express from 'express';import cors from 'cors';import helmet from 'helmet';import cookieParser from 'cookie-parser';import bcrypt from 'bcryptjs';import jwt from 'jsonwebtoken';import pg from 'pg';import crypto from 'crypto';import {z} from 'zod';
const {Pool}=pg, app=express();
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false});
app.use(helmet());
app.use(cors({origin:(origin,cb)=>{const allowed=(process.env.FRONTEND_URL||'').split(',').map(x=>x.trim()).filter(Boolean);if(!origin||!allowed.length||allowed.includes(origin))return cb(null,true);cb(new Error('CORS blocked'))},credentials:true}));
app.use(express.json({limit:'100kb'}));app.use(cookieParser());
const secret=process.env.JWT_SECRET;if(!secret) console.warn('JWT_SECRET is not configured');
const token=u=>jwt.sign({sub:u.id,email:u.email},secret,{expiresIn:'7d'});
const auth=(q,s,n)=>{try{let t=q.cookies.cs_token||String(q.headers.authorization||'').replace(/^Bearer /,'');if(!t)throw 0;q.user=jwt.verify(t,secret);n()}catch{s.status(401).json({error:'Authentication required'})}};
app.get('/api/health',(_,s)=>s.json({ok:true,service:'CyberScore API',version:'1.1.0'}));
app.post('/api/auth/register',async(q,s)=>{try{let d=z.object({businessName:z.string().min(2).max(120),email:z.string().email(),password:z.string().min(8),industry:z.string().min(2).max(80).optional(),size:z.string().max(40).optional()}).parse(q.body),h=await bcrypt.hash(d.password,12),r=await pool.query("INSERT INTO users(business_name,email,password_hash,trial_ends_at,industry,business_size,role) VALUES($1,$2,$3,NOW()+INTERVAL '2 days',$4,$5) RETURNING id,business_name,email,trial_ends_at,industry,business_size,role",[d.businessName,d.email.toLowerCase(),h,d.industry||null,d.size||null]),u=r.rows[0];s.cookie('cs_token',token(u),{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:604800000});s.status(201).json({user:u})}catch(e){s.status(e.code==='23505'?409:400).json({error:e.code==='23505'?'Email already registered':e.message})}});
app.post('/api/auth/login',async(q,s)=>{try{let d=z.object({email:z.string().email(),password:z.string()}).parse(q.body),r=await pool.query('SELECT * FROM users WHERE email=$1',[d.email.toLowerCase()]),u=r.rows[0];if(!u||!(await bcrypt.compare(d.password,u.password_hash)))return s.status(401).json({error:'Incorrect email or password'});s.cookie('cs_token',token(u),{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:604800000});s.json({user:{id:u.id,business_name:u.business_name,email:u.email,trial_ends_at:u.trial_ends_at,industry:u.industry,business_size:u.business_size,role:u.role}})}catch(e){s.status(400).json({error:e.message})}});
app.post('/api/auth/logout',(q,s)=>{s.clearCookie('cs_token');s.json({ok:true})});
app.get('/api/me',auth,async(q,s)=>{let r=await pool.query('SELECT id,business_name,email,trial_ends_at,industry,business_size,role FROM users WHERE id=$1',[q.user.sub]);s.json({user:r.rows[0]})});

// CyberScore Intelligence Engine (CSIE): a transparent, non-invasive baseline risk model for the MVP.
function assess({url,industry,size,emailSecurity}){const u=new URL(url);let score=100,findings=[];const add=(severity,points,title,recommendation)=>{score-=points;findings.push({severity,title,recommendation})};
if(u.protocol!=='https:')add('high',25,'HTTPS is not enabled','Enable HTTPS and redirect HTTP traffic to HTTPS.');
else findings.push({severity:'good',title:'HTTPS is enabled',recommendation:'Continue monitoring certificate validity and TLS configuration.'});
if(u.hostname.includes('xn--'))add('medium',8,'Punycode hostname detected','Verify that the domain is legitimate and expected.');
if(u.hostname.split('.').length<2)add('medium',8,'Unusual domain structure','Verify the public domain configuration.');
if(emailSecurity==='unknown')add('medium',7,'Email security not supplied','Check SPF, DKIM and DMARC configuration during a professional assessment.');
if(size==='micro'||size==='small')findings.push({severity:'info',title:'SME profile detected',recommendation:'Prioritize MFA, backups, least privilege and staff awareness.'});
if(industry==='finance'||industry==='health')add('medium',5,'Higher-impact industry profile','Consider a professionally scoped assessment and applicable compliance review.');
const priority=score>=85?'LOW':score>=70?'MODERATE':score>=50?'HIGH':'CRITICAL';
return {score:Math.max(0,score),priority,engine:'CSIE-1.0',findings};}
app.post('/api/scans',auth,async(q,s)=>{try{let d=z.object({targetUrl:z.string().url(),authorized:z.literal(true),industry:z.string().max(80).optional(),size:z.string().max(40).optional(),emailSecurity:z.enum(['configured','unknown']).optional()}).parse(q.body),result=assess(d);let r=await pool.query('INSERT INTO reports(user_id,target_url,score,findings,authorized,engine,priority) VALUES($1,$2,$3,$4,true,$5,$6) RETURNING *',[q.user.sub,d.targetUrl,result.score,JSON.stringify(result.findings),result.engine,result.priority]);s.status(201).json({report:r.rows[0],assessment:result})}catch(e){s.status(400).json({error:e.message})}});
app.get('/api/news',async(_,s)=>s.json({posts:(await pool.query('SELECT id,title,excerpt,body,category,created_at FROM news WHERE published=true ORDER BY created_at DESC')).rows}));
app.post('/api/news',auth,async(q,s)=>{try{let u=(await pool.query('SELECT role FROM users WHERE id=$1',[q.user.sub])).rows[0];if(u?.role!=='admin')return s.status(403).json({error:'Admin access required'});let d=z.object({title:z.string().min(3).max(180),excerpt:z.string().min(5).max(300),body:z.string().min(10),category:z.string().min(2).max(60)}).parse(q.body);let r=await pool.query('INSERT INTO news(title,excerpt,body,category) VALUES($1,$2,$3,$4) RETURNING *',[d.title,d.excerpt,d.body,d.category]);s.status(201).json({post:r.rows[0]})}catch(e){s.status(400).json({error:e.message})}});
app.get('/api/reports',auth,async(q,s)=>s.json({reports:(await pool.query('SELECT * FROM reports WHERE user_id=$1 ORDER BY created_at DESC',[q.user.sub])).rows}));

const plans={assessment:[50000,'Professional Security Assessment'],audit:[100000,'Industry Standards Audit']};
async function f(path,opt){let r=await fetch((process.env.FAPSHI_BASE_URL||'https://sandbox.fapshi.com')+path,{...opt,headers:{'Content-Type':'application/json',apiuser:process.env.FAPSHI_APIUSER||'',apikey:process.env.FAPSHI_APIKEY||'',...(opt.headers||{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||`Fapshi error ${r.status}`);return d}
app.post('/api/payments/initiate',auth,async(q,s)=>{try{let d=z.object({plan:z.enum(['assessment','audit'])}).parse(q.body),[amount,name]=plans[d.plan];if(!process.env.FAPSHI_APIUSER||!process.env.FAPSHI_APIKEY)return s.status(503).json({error:'Fapshi credentials are not configured'});let user=(await pool.query('SELECT email FROM users WHERE id=$1',[q.user.sub])).rows[0],externalId='CS-'+crypto.randomUUID(),redirect=`${process.env.FRONTEND_URL}/payment-result.html?externalId=${externalId}`,p=await f('/initiate-pay',{method:'POST',body:JSON.stringify({amount,email:user.email,redirectUrl:redirect,userId:q.user.sub,externalId,message:name})});await pool.query('INSERT INTO payments(user_id,external_id,trans_id,amount,service,status,link) VALUES($1,$2,$3,$4,$5,$6,$7)',[q.user.sub,externalId,p.transId,amount,d.plan,'PENDING',p.link]);s.json({paymentUrl:p.link,externalId,transId:p.transId})}catch(e){s.status(502).json({error:e.message})}});
app.get('/api/payments/status/:id',auth,async(q,s)=>{let r=await pool.query('SELECT * FROM payments WHERE external_id=$1 AND user_id=$2',[q.params.id,q.user.sub]);if(!r.rows[0])return s.status(404).json({error:'Payment not found'});s.json({payment:r.rows[0]})});
app.post('/api/webhooks/fapshi',async(q,s)=>{try{if(process.env.FAPSHI_WEBHOOK_SECRET&&q.headers['x-wh-secret']!==process.env.FAPSHI_WEBHOOK_SECRET)return s.status(401).json({error:'Invalid webhook secret'});let p=q.body;if(!p.externalId)return s.status(400).json({error:'Missing externalId'});await pool.query('UPDATE payments SET status=$1,trans_id=COALESCE($2,trans_id),updated_at=NOW() WHERE external_id=$3',[p.status,p.transId,p.externalId]);s.json({ok:true})}catch{s.status(500).json({error:'Webhook failed'})}});
app.get('/api/payments',auth,async(q,s)=>s.json({payments:(await pool.query('SELECT external_id,trans_id,amount,service,status,created_at FROM payments WHERE user_id=$1 ORDER BY created_at DESC',[q.user.sub])).rows}));
app.listen(process.env.PORT||8080,()=>console.log('CyberScore API running'));
